name: Build and deploy ASP app to Azure Web App - TM-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore NuGet packages
        run: dotnet restore src/YourProject/YourSolution.sln
        working-directory: .  # 確保工作目錄正確

      - name: Build project
        run: dotnet build --configuration Release src/YourProject/YourSolution.sln
        working-directory: .  # 確保工作目錄正確

      - name: Publish project
        run: dotnet publish -c Release -o published src/YourProject/YourSolution.sln
        working-directory: .  # 確保工作目錄正確

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app  # Artifact 名稱
          path: src/YourProject/published/ASPtest  # 確保路徑正確

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app  # Artifact 名稱
          path: downloaded-artifact  # 下載到指定目錄

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15B2F3CBF05C4C8FA27207766F21121F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A3E10368EB6A4B659B1CCC6AABBE2E9C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4414053102F2416980B41469258A9B0C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TM-web'
          slot-name: 'Production'
          package: 'downloaded-artifact'  # 指定下載的 Artifact 目錄
